[profile.default]
src = "src"
out = "out"
libs = ["lib"]

ast = true
build_info = true
extra_output = ["storageLayout"]
# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200
# Whether or not to use the Yul intermediate representation compilation pipeline
via_ir = true
# Override the Solidity version (this overrides `auto_detect_solc`)
evm_version = "cancun"
solc_version = "0.8.20"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }